version: "3.7"
services:

  workbench:
    image: codingmatters/nosql-workbench:1.2.0
    volumes:
      - "./workspace:/usr/src/app/workspace"
    ports:
      - "9999:8080"
    command: ["node", "app.js", "--server"]

  mongo:
    image: mongo:4.2.2

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    environment:
      - discovery.type=single-node
    ports:
    - "9200:9200"

  cassandra:
    image: cassandra:4.0.1

  redis:
    image: redis:5
